<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo URL_PATH; ?>" /><!--[if lte IE 6]></base><![endif]-->
        <meta charset="<?php echo APP_CHARSET ?>" />
        <meta charset="utf-8">
        <title>Kubox3 -> CMS</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        
        <!-- Le styles -->
        <link href="css/bootstrap.css" rel="stylesheet">
        <style>
        body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
        </style>
        <link href="css/bootstrap-responsive.css" rel="stylesheet">
        <link href="css/admin.css" rel="stylesheet">
        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        
        <!-- Fav and touch icons -->
        <link rel="shortcut icon" href="ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">
        <?php Tag::css( 'codemirror' ) ?>
        <?php echo Html::includeCss() ?>
    </head>
    <body>    
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand">Kubox3</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                        <?php
                        foreach ( array( 'tables', 'fields', 'initialize', 'classes', 'methods', 'templates', 'pages', 'boxes', 'files' ) as $link )
                        {
                          $active = ( $link == $controller_name ) ? ' class="active"': '';
                          echo "<li$active><a href=\"admin/$link\">" . ucfirst( $link ) . "</a></li>";
                        }
                        ?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        
        <div class="container">
        <?php View::content(); ?>
        </div>
        
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="javascript/bootstrap.min.js"></script>
        <script src="javascript/admin.js"></script>
        <script src="javascript/textarea_tabs.js"></script>
    </body>
</html>