
<script src="/javascript/codemirror.js"></script>
<!--<script src="/javascript/codemirror/php/php.js"></script>-->
<script>
var editor = CodeMirror.fromTextArea(document.getElementById("css"),
{
	height: "350px",
	lineNumbers: true
});
									 
/* CODEMIRROR
var code_type = '';
$( '.codemirror' ).each( function( index )
{
	$( this ).attr( 'id', 'codemirror' + index );
	CodeMirror.fromTextArea( document.getElementById( 'codemirror' + index ),
	{
        height: "350px",
		lineNumbers: true,
		mode: "php"
	});
}); */
</script>
