
<div class="row">
	<div class="span7">
		<form action="admin/<?php echo $controller_name; ?>/add" method="post">
			<input class="span2" name="name" placeholder="Name" type="text" value="<?php _::eo( $script_selected, 'name' ); ?>" />
			<input class="span1" name="weight" placeholder="Weight" type="text" value="<?php _::eo( $script_selected, 'weight' ); ?>" />
			<textarea class="span7" name="code" rows="12"><?php _::eo( $script_selected, 'code' ); ?></textarea>
			<div class="navbar navbar-inverse navbar-fixed-bottom">
				<div class="navbar-inner">
					<button class="btn btn-success" data-action="admin/<?php echo $controller_name; ?>/add" data-target="_self" type="submit"><i class="icon-plus icon-white"></i> Create</button>
					<?php
					if ( _::o( $script_selected, 'id' ) )
					{
						?>
						<button class="btn btn-warning" data-action="admin/<?php echo $controller_name; ?>/edit/<?php echo $script_selected->id; ?>" data-target="_self" type="submit"><i class="icon-ok icon-white"></i> Update</button>
						<button class="btn btn-danger" data-action="admin/<?php echo $controller_name; ?>/quit/<?php echo $script_selected->id; ?>" data-target="_self" type="submit"><i class="icon-remove icon-white"></i> Delete</button>
						<?php
					}
					?>
				</div>
			</div>
		</form>
	</div>
	<?php
	if ( $scripts )
	{
		?>
		<div class="span3">
			<ul class="unstyled">
				<?php
				foreach ( $scripts as $script )
				{
					?>
					<li>
						<a href="admin/initialize/quit/<?php echo $script->id; ?>" class="icon-remove"></a>
						<a href="admin/initialize/index/<?php echo $script->id; ?>"><?php echo $script->name; ?></a> <sup><?php echo $script->weight; ?></sup>
					</li>
					<?php
				}
				?>
			</ul>
		</div>
		<?php
	}
	?>
</div>
